name: BlockTracker
version: '1.3'
main: org.kxysl1k.blockTracker.BlockTracker
api-version: '1.21'
authors: [ Kxysl1k ]
description: A plugin that adds a special brush to interact with blocks and players. Plugin By Kxysl1k
website: https://kxysl1k.netlify.app/
depend: [CoreProtect]
commands:
  getwand:
    description: Get a magic wand
    usage: /getwand